// vent launcher.
// executable.
// ——————————————————————
//
// this is the default launcher for vent. it is intentionally minimalistic.
// it loads the engine library, calls the engine entry point and passes the
// configuration from the generated build info header.

#include <_vent/vent_sdk.hpp>

#ifdef _WIN32
    #ifndef WIN32_LEAN_AND_MEAN
        #define WIN32_LEAN_AND_MEAN
    #endif
    #ifndef NOMINMAX
        #define NOMINMAX
    #endif
    #include <windows.h>
#else
    #include <dlfcn.h>
#endif

#include <print>
#include <string>

// this is set by cmake via vent_create_client.
#ifndef VENT_APP_ID
    #define VENT_APP_ID vent_unknown
#endif

// helper macros for stringification and token pasting.
#define VENT_STRINGIFY_IMPL(x) #x
#define VENT_STRINGIFY(x) VENT_STRINGIFY_IMPL(x)
#define VENT_CONCAT_IMPL(a, b) a##b
#define VENT_CONCAT(a, b) VENT_CONCAT_IMPL(a, b)

// generated by cmake. contains plugin lists and app info.
// expands to: #include "minimal_build_info.hpp" (for VENT_APP_ID=minimal).
#include VENT_STRINGIFY(VENT_CONCAT(VENT_APP_ID, _build_info.hpp))

namespace {

#ifdef _WIN32
constexpr const char* SHARED_LIB_PREFIX = "lib";
constexpr const char* SHARED_LIB_SUFFIX = ".dll";
using lib_handle                        = HMODULE;
constexpr lib_handle INVALID_LIB_HANDLE = nullptr;
#elif defined(__linux__)
constexpr const char* SHARED_LIB_PREFIX = "lib";
constexpr const char* SHARED_LIB_SUFFIX = ".so";
using lib_handle                        = void*;
constexpr lib_handle INVALID_LIB_HANDLE = nullptr;
#elif defined(__APPLE__)
constexpr const char* SHARED_LIB_PREFIX = "lib";
constexpr const char* SHARED_LIB_SUFFIX = ".dylib";
using lib_handle                        = void*;
constexpr lib_handle INVALID_LIB_HANDLE = nullptr;
#endif

/// @brief base name of the engine shared library without prefix or suffix.
/// @note usually, the library is called `libvent_engine.<EXT>`.
constexpr const char* ENGINE_LIB_BASE = "vent_engine";

/// @brief name of the engine main entry function.
constexpr const char* ENGINE_MAIN_ENTRY = "vent_engine_entry";

inline auto load_lib(const char* path) -> lib_handle {
#ifdef _WIN32
    return LoadLibraryA(path);
#else
    return dlopen(path, RTLD_NOW | RTLD_GLOBAL);
#endif
}

inline auto unload_lib(lib_handle handle) -> void {
    if (handle == INVALID_LIB_HANDLE)
        return;
#ifdef _WIN32
    FreeLibrary(handle);
#else
    dlclose(handle);
#endif
}

template <typename T>
inline auto get_lib_symbol(lib_handle handle, const char* name) -> T {
    if (handle == INVALID_LIB_HANDLE || name == nullptr)
        return nullptr;
#ifdef _WIN32
    return reinterpret_cast<T>(GetProcAddress(handle, name));
#else
    return reinterpret_cast<T>(dlsym(handle, name));
#endif
}

}  // namespace

// --- main entry point ---
// —————————————————————————————————————————————————————————————————————————————

auto main(int argc, char** argv) -> int {
    TIC;
    std::string engine_path = std::string("./") + SHARED_LIB_PREFIX +
                              ENGINE_LIB_BASE + SHARED_LIB_SUFFIX;

    std::print("[launcher] loading engine library: {}\n", engine_path);

    // load engine library.
    auto engine_handle = load_lib(engine_path.c_str());
    if (engine_handle == INVALID_LIB_HANDLE) {
        std::print("[launcher] error: failed to load engine library\n");
        return 1;
    }

    // find engine main function.
    auto engine_main = get_lib_symbol<vent::vent_engine_entry_fn>(
        engine_handle, ENGINE_MAIN_ENTRY);
    if (engine_main == nullptr) {
        std::print("[launcher] error: main entry point `{}` not found.\n",
                   ENGINE_MAIN_ENTRY);
        unload_lib(engine_handle);
        return 1;
    }

    std::print("[launcher] starting vent engine. application: {}\n\n",
               vent::generated::app_id);

    // build engine configuration from generated build info.
    // note: plugins[] contains only startup plugins (STARTUP_PLUGINS + client).
    // other plugins (PLUGINS without STARTUP_PLUGINS) are loaded dynamically
    // by systems at runtime (e.g., renderer loads vulkan_backend).
    vent::engine_config config {.app_id       = vent::generated::app_id,
                                .plugins      = vent::generated::plugins,
                                .plugin_count = vent::generated::plugin_count,
                                .argc         = argc,
                                .argv         = argv};

    // fire up engine.
    int result = engine_main(config);

    // clean up and exit.
    std::print(
        "\n[launcher] vent engine has exited. unloading engine library...\n");
    unload_lib(engine_handle);

    std::print("[launcher] exiting with: {}\n", result);

    TOC;
    return result;
}
