// vent launcher.
// executable.
// ——————————————————————
//
// this is the default launcher for vent. it is intentionally minimalistic.
// it loads the engine library, calls the engine entry point and passes the
// configuration from the generated build info header.

#include <_vent/vent_sdk.hpp>
#include <_vent/platform/library.hpp>

#include <print>
#include <string>

// this is set by cmake via vent_create_client.
#ifndef VENT_APP_ID
    #define VENT_APP_ID vent_unknown
#endif

// helper macros for stringification and token pasting.
#define VENT_STRINGIFY_IMPL(x) #x
#define VENT_STRINGIFY(x) VENT_STRINGIFY_IMPL(x)
#define VENT_CONCAT_IMPL(a, b) a##b
#define VENT_CONCAT(a, b) VENT_CONCAT_IMPL(a, b)

// generated by cmake. contains plugin lists and app info.
// expands to: #include "minimal_build_info.hpp" (for VENT_APP_ID=minimal).
#include VENT_STRINGIFY(VENT_CONCAT(VENT_APP_ID, _build_info.hpp))

namespace {

/// @brief base name of the engine shared library without prefix or suffix.
/// @note usually, the library is called `libvent_engine.<EXT>`.
constexpr const char* ENGINE_LIB_BASE = "vent_engine";

/// @brief name of the engine main entry function.
constexpr const char* ENGINE_MAIN_ENTRY = "vent_engine_entry";

}  // namespace

// --- main entry point ---
// —————————————————————————————————————————————————————————————————————————————

auto main(int argc, char** argv) -> int {
    std::string engine_path =
        "./" + vent::lib::make_shared_library_name(ENGINE_LIB_BASE);

    std::print("[launcher] loading engine library: {}\n", engine_path);

    // load engine library.
    auto engine_handle = vent::lib::load_library(engine_path.c_str());
    if (engine_handle == vent::lib::INVALID_LIBRARY_HANDLE) {
        std::print("[launcher] error: failed to load engine library: {}\n",
                   vent::lib::get_last_error());
        return 1;
    }

    // find engine main function.
    auto engine_main =
        vent::lib::get_library_symbol_as<vent::vent_engine_entry_fn>(
            engine_handle, ENGINE_MAIN_ENTRY);
    if (engine_main == nullptr) {
        std::print("[launcher] error: main entry point `{}` not found.\n",
                   ENGINE_MAIN_ENTRY);
        vent::lib::unload_library(engine_handle);
        return 1;
    }

    std::print("[launcher] starting vent engine. application: {}\n\n",
               vent::generated::app_id);

    // build engine configuration from generated build info.
    // note: plugins[] contains only startup plugins (STARTUP_PLUGINS + client).
    // other plugins (PLUGINS without STARTUP_PLUGINS) are loaded dynamically
    // by systems at runtime (e.g., renderer loads vulkan_backend).
    vent::engine_config config {.app_id       = vent::generated::app_id,
                                .plugins      = vent::generated::plugins,
                                .plugin_count = vent::generated::plugin_count,
                                .argc         = argc,
                                .argv         = argv};

    // fire up engine.
    int result = engine_main(config);

    // clean up and exit.
    std::printf(
        "\n[launcher] vent engine has exited. unloading engine library...\n");
    vent::lib::unload_library(engine_handle);

    std::printf("[launcher] exiting with: %d\n", result);

    return result;
}
